### ISSUE TITLE
Pros/cons vs json-rpc-server

### ISSUE THREAD

**Issue by obadz** [xenog/json-rpc#3]
I'm looking to write a json-rpc server in Haskell and I see that there are two packages: json-prc and json-rpc-server (https://github.com/grayjay/json-rpc-server).  Would you mind briefly mentioning why one would use one vs the other?

Thanks

**Comment by xenog** [comment]
I have not tried json-rpc-server myself, but I can tell you that you may want to use my package if you:
- are implementing a JSON-RPC client over sockets,
- want to support both versions of the JSON-RPC protocol,
- need to be able to send and receive notifications,
- need client and server capabilities in each host,
- are implementing a P2P application with JSON-RPC as protocol.

The most complex implementation of JSON-RPC is the client, due to matching responses to requests based on the id. The server is relatively easy to write. I am sure any server implementation will do for basic code.

**Comment by obadz** [comment]
Thanks @xenog
